[pytest]

addopts =
    -v
    --tb=short
    --reruns 1
    --alluredir=allure-results
    --junitxml=junit.xml

testpaths = tests

python_files = test_*.py

python_classes = Test*

python_functions = test_*

markers =
    smoke
    regression
    sanity